### ISSUE TITLE
Remove gov.uk icons

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/notify#246]
I'm not sure if they are there intentionally? 

https://realfavicongenerator.net/favicon_checker?protocol=http&site=notify.gov.au

![image](https://user-images.githubusercontent.com/20184809/60310094-88275780-9994-11e9-8d4f-45822571be12.png)

**Comment by jonathaningram** [comment]
@sukhrajghuman thanks for this, it's an oversight. We'll address it ❤️

**Comment by jonathaningram** [comment]
Thanks @sukhrajghuman resolved.
